version: '3'
services:
  backend:
    image: your-dockerhub-username/courses-api
    ports:
      - "8000:8000"
  frontend:
    image: your-dockerhub-username/courses-frontend
    ports:
      - "3000:3000"
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: courses
